services:
  ianseodb:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-ianseo}
      - MARIADB_USER=${MARIADB_USER:-ianseo}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-ianseo}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-ianseo}
    restart: always
  ianseo:
    image: arqueria/ianseo
    ports:
      - "8080:80"
    depends_on:
      - ianseodb
    # restart: always
