services:
  ianseodb:
    image: mariadb:10
    environment:
      - MARIADB_ROOT_PASSWORD=ianseo
      - MARIADB_USER=ianseo
      - MARIADB_DATABASE=ianseo
      - MARIADB_PASSWORD=ianseo
  ianseo:
    image: ecelis/ianseo-docker:m-1
    ports:
      - "8080:80"
    depends_on:
      - ianseodb
