<?php
$lang['AuthTourCode']='Elenco separato da virgole dei codici gara gestibili dall\'utente.<br>Carattere jolly ammesso: "%"';
$lang['AutoCheckinAlreadyDone']='Hai già effettuato il check-in<br>Se hai bisogno di modificare qualsiasi informazione, procedi al banco dell\'accreditamento';
$lang['AutoCheckinConfirm']='Se tutti i dati sono corretti premi CONFERMA CHECK-IN<br> Altrimenti premi ANNULLA e procedi al DESK di accreditamento';
$lang['AutoCheckinSearch']='Scansiona il QR-Code che hai ricevuto o digita il tuo nome';
$lang['AutoCHK-CanEdit']='Consenti agli operatori del check-in di modificare nomi, e-mail, Paese/Società, ecc.';
$lang['AutoCHK-Code']='Elenco delle competizioni, una per riga<br> Il primo codice competizione sarà utilizzato come intestazione postazioni di Self Service Kiosks';
$lang['AutoCHK-IP']='Elenco degli IP dei dispositivi di check-in automatico. Un indirizzo IP per linea';
$lang['AutoCHK-IPinfo']='Elenco degli IP dei punti informativi self-service. Un indirizzo IP per riga';
$lang['AutoCHK-IPnoMgm']='Lista degli IP delle postazioni Self check-in Kiosks. Un indirizzo IP per linea, corrispondente a uno dei seguenti formati:<br> IP del Dispositivo<br> IP del Dispositivo | Coda di stampa per l\'accreditamento <br> IP del Dispositivo | Coda di stampa per l\'accreditamento | Coda di stampa dei cartellini con il nome<br> Coda di stampa nel modulo: Nome coda [ @ Server di stampa ]';
$lang['AutoCHK-Print']='Mostra automaticamente la finestra di dialogo di stampa';
$lang['AutoImportSettings']='<b>Solo per Utenti Esperti</b><br>Cambiare i parametri di default può portare ad avere risultati non precisi.<br> E\' importante ricalcolare tutte le rank degli eventi che sono stati impostati manualmente PRIMA di inviare i risultati a ianseo.net o stampare i risultati e, in generale, sempre prima di fare qualsiasi tipo di distribuzione.';
$lang['ChangeComponents']='<p>Per procedere con un cambio di componente, prima togliere l\'atleta che non è più nel team in modo da poter attivare le opzioni di sostituzione.</p> &#9654&nbsp;Punteggi inclusi nel totale del team nella fase di qualifica<br> &#9655&nbsp;Punteggi non inclusi nel totale del team nella fase di qualifica';
$lang['CombiCompList']='Elenco dei Codici Competizione, separati da virgole';
$lang['ExportAdvanced']='Esporta anche i dati dei partecipanti e del Paese/Società da fornire se mancanti al Destinatario';
$lang['ExportCategories']='Scegliere quali Div.Cl/eventi esportare (nessuna selezione significa tutte)';
$lang['ExportDistances']='Seleziona quali distanze esportare (nessuna selezione significa tutte le distanze)';
$lang['ExportSchedule']='Seleziona dal programma di gara il turno da esportare';
$lang['ExportScheduleToday']='Mostra solo i turni programmati per oggi';
$lang['FlightsManagement']='<b>Ai raggruppamenti per categorie</b> <ul> <li>Selezionare in quale Voleé-Totale di Distanza-Totale Completo calcolare i raggruppamenti;</li> <li>Selezionare la dimensione iniziale della riduzione di raggruppamento per categoria. Il sistema precarica la tabella di raggruppamento standard NFAA quando la competizione lo consente;</li> <li>L\'anteprima del raggruppamento calcolerà TUTTE LE CATEGORIE; premete il pulsante di ricarica a lato della dimensione della riduzione di raggruppamento per forzare il calcolo di una singola categoria; </li> <li>I raggruppamenti contrassegnati con l\'arancione sono solo un indicatore di una differenza tra l\'anteprima dei raggruppamenti e la tabella delle regole. NON influisce sulla divisione del raggruppamento;</li> <li>Usare i comandi “Elimina”, “Separa” e “Unisci” per regolare le informazioni sui raggruppamenti. Si noti che dopo aver eseguito un\'anteprima completa o un aggiornamento delle categorie, tutte le modifiche apportate al raggruppamento vengono perse;</li> </ul> <b>Note</b> <ul> <li>Le categorie con un numero troppo basso di partecipanti vengono escluse dal raggruppamento. Il raggruppamento può essere forzato indicando la quantità di riduzione del raggruppamento;</li> <li>Se una categoria è considerata raggruppabile, utilizzare \'-1\' come riduzione per escluderla esplicitamente dal processo di raggruppamento.</li> <li>Professionisti e/o Campionati sono esclusi dal raggruppamento e sono contrassegnati in grigio</li> </ul>';
$lang['FontFamily']='Nome del carattere da utilizzare nel CSS';
$lang['FontFile']='Posizione del file sul disco';
$lang['FontName']='Nome effettivo del carattere';
$lang['FontStyle']='Stile del carattere in CSS';
$lang['FontWeight']='Peso del carattere in CSS';
$lang['GetBarcodeSeparator']='Dopo aver stampato la pagina con i riferimenti dei Codici a Barre, leggi con la pistola il codice a barre "SEPARATORE" in modo da attivare il corretto lettore';
$lang['HomePage']='Questa è la pagina dove puoi selezionare o creare un Torneo';
$lang['ISK-LockedSessionHelp']='L\'icona {$a} indica se la app può inserire o meno dei punteggi nella sessione';
$lang['ISK-ServerUrlPin']='<b>NON RIVELARE QUESTO NUMERO</b><br>Scegli un PIN (4 Cifre Numeriche) da usare per accedere alla tua competizione.<br>I Dispositivi potranno inviare punteggi alla tua gara solo leggendo il QR-Code che viene stampata da IANSEO.<br> In caso di inserimento manuale dei dati di gara nella app Ianseo Scorekeeper LITE, Il codice competizione da usare è <b>{$a}</b>';
$lang['QrCodeLandscape']='Un singolo o doppio "<" disegnerà una freccia che punta a sinistra. Un singolo o doppio ">" disegnerà una freccia che punta a destra. Un singolo o doppio "^" disegnerà una freccia che punta in alto. Una singola o doppia "v" disegnerà una freccia che punta verso il basso.';
$lang['QrCodePortrait']='Il campo è compatibile con HTML. Se inserisci qualcosa circondato da &lt;qrcode&gt;...&lt;/qrcode&gt;  il contenuto verrà modificato in un QR-Code';
$lang['ScoreBarCodeShortcuts']='Leggi il Codice a Barre stampato sullo Score.
Inserendo # seguito dal nome di un atleta si cerca nel database questo atleta.
Inserendo @ seguita dal numero di piazzola si cerca nel database questa piazzola. La distanza DEVE essere specificata. La sessione può essere specificata (primo numero) e il numero della piazzola deve essere composto da 3 cifre';
$lang['ScoreboardFreetext-Texts']='Inserisci {{date}} per inserire la data in formato inglese (es: january 4, 2024)<br> Inserisci {{date-lang}} per inserire una data nella lingua locale (es: {{data-de}} per avere 4 gennaio 2024)<br> Inserisci {{time}} per avere l\'ora che scorre in formato ISO (es: 15:03:23)<br> Inserisci {{time-am}} per avere l\'ora che scorre in formato AM/PM (es: 3:03:23 PM)<br> Inserisci {{counter-datetime}} per avere un countdown completo della data (es: [[[giorni:]ore:]minuti:]secondi, dove "datetime" è l\'ora da raggiungere nel formato ISO 2024-12-04T09:00:00 per l\'ora locale)<br> In un testo può essere presente solo uno di questi campi';
$lang['TargetRequests-Printout']='Stampa i QrCode dei bersagli richiesti per consentire ai dispositivi personali di essere riassegnati rapidamente al bersaglio corretto.<br> Seleziona il/i gruppo/i di dispositivi che vuoi stampare e l\'intervallo delle piazzole di interesse:<br> 1-10 stamperà i Qr-Code dal bersaglio 1 al 10<br> 1,7,12-15 stamperà i Qr-Code dei bersagli 1,7 e dal bersaglio 12 al 15';
$lang['TargetScoring-Printout']='Stampa i QR-Code dei bersagli richiesti per inserire i punti nella Sessione-Piazzola-Distanza richieste con l\'ISK NG Lite. È lo stesso QR-Code presente sullo score<br>Seleziona il/i turno/i di gara che vuoi stampare e l\'intervallo delle piazzole di interesse: 1-10 stamperà i Qr-Code dal bersaglio 1 al 10<br> 1,7,12-15 stamperà i Qr-Code dei bersagli 1,7 e dal bersaglio 12 al 15';
$lang['TV-ChannelSetup']='<b>CONFIGURAZIONE DEI CANALI</b><br>
<br>
Dopo aver impostato i canali come si desiderano, collega il browser del dispositivo che vuoi collegare a un canale a <code>http://IP.DI.IANSEO/tv.php?Id=CANALE</code> dove <b>IP.DI.IANSEO</b> è l\'IP su cui è in esecuzione ianseo (inclusa la directory se presente) e <b>CANALE</b> \'è l\'ID del canale';
$lang['TV-RotEdit']='<div>Una pagina di presentazione è composta da almeno una pagina di contenuto.</div><div>Le pagine di contenuto verranno quindi mostrate una dopo l\'altra e ricominceranno daccapo.</div> <div><b> NOTA:</b> nei motori di versione normale e leggera, il primo contenuto viene nuovamente mostrato come ultimo, è quindi consigliabile inserire come primo contenuto un\'immagine (ad esempio il logo della competizione).</div> <div> I contenuti possono essere inerenti alla competizione (elenco piazzole, qualifiche, scontri...) oppure "multimediali" (immagini, messaggi HTML, ...).</div>';
$lang['TV-RotEdit-DB']='<h2>Gestione CSS3 (motore avanzato)</h2><h3>Unità di lunghezza</h3><ul><li><b>rem:</b> altezza del carattere principale</li><li><b>em:</b>altezza del carattere corrente</li><li><b>ex:</b>altezza della "x"minuscola</li><li><b>ch: </ b> larghezza del numero "0"</li><li><b>vh:</b>un centesimo dell\'altezza dello schermo</li><li><b>vw:</b> un centesimo della larghezza dello schermo</li><li><b>vmin:</b> un centesimo del valore minimo tra l\'altezza e la larghezza dello schermo</li><li><b>vmax:</b> un centesimo del valore massimo tra l\'altezza e la larghezza dello schermo</li></ul><h3> Box flessibili</h3><li><b>contrai ABC:</b><ul><li><b>A</b>: se 0 significa che la casella non può espandersi; se> 1 significa che la casella può espandersi a quella "velocità" rispetto ad altre caselle (se la casella 1 ha 2 e la casella 2 ha 3, la casella 2 si espanderà di 1,5 in più rispetto alla casella 1 che a sua volta si espanderà il doppio di una casella con questo valore impostato a 1)</li><li><b>B:</b> se 0 il box non può ridursi; se 1 il box può ridursi</li><li> <b>C:</b> dimensione iniziale del box</li></ul></li><h3>Riferimento CSS</h3><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Reference">https://developer.mozilla.org/en-US/docs/Web/CSS/Reference</a>';
$lang['TV-RotList']='<div>Questo è l\'elenco delle pagine di presentazione disponibili da inviare a maxischermi, monitor o broadcast.</div><div> Sono forniti 3 diversi motori, fare clic sul collegamento per attivarli:</div><ul><li>un normale motore compatibile con la maggior parte dei browser</li><li>una versione leggera del motore compatibile con la maggior parte dei browser ma che utilizza meno risorse</li><li>una versione avanzata che utilizza i browser moderni funzionalità HTML5</li></ul><div>Per creare un nuovo contenuto, inserisci un nome e premi il pulsante.</div>';
$lang['UserName']='Deve essere unico nel Sistema. Lunghezza minima: 6 caratteri';
$lang['UserPassword']='Lasciare vuoto per mantenere la password corrente';
$lang['ZeroBased']='Numero a base zero';
?>