theme: jekyll-theme-tactile
domain: ecelis.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ecelis.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /ianseo/      # place folder name if the site is served in a subfolder
